### ISSUE TITLE
Custom element doesn't exist (Samsung Family Hub)

### ISSUE THREAD

**Issue by susenstoob** [punxaphil/custom-sonos-card#312] opened 2024-03-06 06:28 UTC
**Checklist:**

- [X ] I updated to the latest version available
- [X ] I cleared the cache of my browser

**Release with the issue:**
7.1.1
**Last working release (if known):**
N/A
**Browser and Operating System:**
Samsung Family Hub, browser unknown but assuming chromium 

**Description of problem:**
First off, what a cool ass card. I love this card! Thank you so much, it is EXACTLY what I need to do multi room sonos control from my HA dashboard! 

So this card works everywhere except on my refridgerator (Samsung Family Hub). Works on iOS, desktop (mutli browsers) but I am getting this error on my fridge (which sadly IS my HA dashboard right now as I havent yet wall mounted a tablet):

Custom element doesn't exist: sonos-card
type:custom:sonos-card
sections:
-player
-volumes
-groups
-grouping
-media browser
widthPercentage: 200
heightPercentage: 200
topFavorites:
-"
dynamicVolumeSlider: true

I installed via HACs and havent done any yaml editing.

Thanks!

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by punxaphil** [comment] 2024-03-06 06:42
duplicate of https://github.com/punxaphil/custom-sonos-card/issues/238

**Closed** 2024-09-27 16:03 UTC
Labels: bug
