### ISSUE TITLE
Custom Element does not exist - android app

### ISSUE THREAD

**Issue by FPF92** [punxaphil/custom-sonos-card#510] opened 2024-10-15 22:25 UTC
I am running the home assistant app for android on an android 10 wall mounted tablet. The problem is, that it always displays the error custom element doesn't exist: Sonos-Card.

I already flushed the cash and reinstalled the app. 

However the card is shown on the same dashboard and same user on the iOS app and on the android tablet on native chrome browser.

Can somebody help me?

**Comment by punxaphil** [comment] 2024-10-16 20:07
Duplicate of https://github.com/punxaphil/custom-sonos-card/issues/51

**Closed by punxaphil** 2024-10-16 20:07 UTC
Labels: bug
