### ISSUE TITLE
Playlist and Podcasts Not Showing in Favorites

### ISSUE THREAD

**Issue by crobz** [punxaphil/custom-sonos-card#452] opened 2024-08-28 16:38 UTC
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
v7.11.2 of Sonos Card
v2.0.0 of HACS

**Last working release (if known):**
New to HA, never had this working before

**Browser and Operating System:**
Chrome, MacOS

**Description of problem:**
The media browser only provides radio station favorites -- I cannot get it to show playlists or podcast favorites. 
I also am not seeing new integrations connected through sonos, but that may just be a time delay and/or separate issue.
[
![HASonosCardFavorites](https://github.com/user-attachments/assets/ddc993cc-89e3-4530-ac4b-9ca4802816e8)
![sonosFavorites](https://github.com/user-attachments/assets/5d032c06-a99c-4e8d-bba9-cbdf8bd76823)
](url)

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by motoridersd** [comment] 2024-09-06 16:54
I've noticed that since the Sonos app update, any favorited Playlists aren't working properly. Playlists favorited before the app update continue to work, but any new ones addede are either empty and don't work, or don't even show up anymore.

**Comment by punxaphil** [comment] 2024-09-09 21:04
That is not true for me. I've added since then, and it works fine. Must be some glitch on your end I am afraid.

**Comment by punxaphil** [comment] 2024-09-09 21:05
I cannot reproduce this. My extensive testing constantly shows that this is working. Closing since I am not able to fix something that is working for me.

**Closed by punxaphil** 2024-09-09 21:05 UTC
Labels: bug

**Comment by punxaphil** [comment] 2024-10-15 21:56
@crobz @motoridersd 
You can add custom favorites if you still have this issue: https://github.com/punxaphil/custom-sonos-card?tab=readme-ov-file#custom-favorites--sources


---
PunxaPhil
[![image](https://github.com/user-attachments/assets/cb2e240e-f9ca-4900-a425-b8089216c1ee)](https://patreon.com/PunxaPhil) [![image](https://github.com/johanfrick/custom-sonos-card/assets/26582898/9bebc1f6-6bda-4cbd-b596-50d3d2f712de)](https://www.buymeacoffee.com/punxaphil)
