### ISSUE TITLE
Uncaught Error from Chrome Webview (Same as #336)

### ISSUE THREAD

**Issue by BobRobertBob** [punxaphil/custom-sonos-card#489] opened 2024-10-03 19:36 UTC
**Checklist:**

- [x ] I updated to the latest version available
- [x ] I cleared the cache of my browser

**Release with the issue:**
v7.14.0
**Last working release (if known):**
Has been an issue for me with all previous releases
**Browser and Operating System:**
Windows Chrome, Android Chrome, IOS

**Description of problem:**

Errors are generated anytime I access a Dashboard with the Sonos Card, I don't have to click on the card. I tried "ha core rebuild" mentioned in #336, no change. Not running Spotify. No issue with the functionality of the card itself.  This happens on Windows (Chrome) as well as on two different Androids and IOS.

From Logs:

Logger: frontend.js.modern.202409091
Source: components/system_log/init.py:333
First occurred: 10:13:36 AM (9 occurrences)
Last logged: 10:19:34 AM

Uncaught error from Chrome WebView 128.0.6613.146 on Android 14 ReferenceError: Cannot access 'e' before initialization Object.callback (/hacsfiles/custom-sonos-card/custom-sonos-card.js:381:980) callback (node_modules/home-assistant-js-websocket/dist/connection.js:23:33) forEach (node_modules/home-assistant-js-websocket/dist/connection.js:15:25)

Uncaught error from Chrome 129.0.0.0 on Windows 10 ReferenceError: Cannot access 'e' before initialization Object.callback (/hacsfiles/custom-sonos-card/custom-sonos-card.js:381:980) callback (node_modules/home-assistant-js-websocket/dist/connection.js:23:33) forEach (node_modules/home-assistant-js-websocket/dist/connection.js:15:25)

Uncaught error from Chrome WebView 120.0.6099.266 on Android 11 ReferenceError: Cannot access 'e' before initialization Object.callback (/hacsfiles/custom-sonos-card/custom-sonos-card.js:381:980) callback (node_modules/home-assistant-js-websocket/dist/connection.js:23:33) forEach (node_modules/home-assistant-js-websocket/dist/connection.js:15:25)

Explain what the issue is, and how things should look/behave. If possible provide a screenshot with a description.
-->

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by deluxestyle** [comment] 2024-10-07 09:39
having the same issue

**Comment by deluxestyle** [comment] 2024-10-18 14:17
Error still Shows up everytime I use the Card. Even with the app

**Comment by deluxestyle** [comment] 2024-10-28 14:11
@punxaphil anything that I can help. what kind of information do you need?

**Comment by punxaphil** [comment] 2024-10-28 14:12
In the browser's dev tools, try to debug the running code hacsfiles/custom-sonos-card/custom-sonos-card.js:381:980 to see if you can see the reason why it is failing

**Comment by deluxestyle** [comment] 2024-10-28 14:31
I guess I get the issue
the issue only appears if the first device in the list is not available. as long all my Sonos speakers are available the issue is not there. 
As soon my first player goes offline, the issue shows up

**Comment by deluxestyle** [comment] 2024-10-28 14:36
was not really able to debug but I can see additional errors in the javascript console

`log-message.ts:36 
        
        
       GET https://xxx/hacsfiles/custom-sonos-card/custom-sonos-card.js.map 404 (Not Found)
       GET https://xxx/unknown/node_modules/home-assistant-js-websocket/dist/connection.js 404 (Not Found)`

**Comment by punxaphil** [comment] 2024-10-28 14:39
You get the same error no matter if you connect to internal hostname or through https?
E.g.:
Internal: http://homeassistant.local:8123
External: https://mypublicdomain.example.com

**Comment by deluxestyle** [comment] 2024-10-28 14:41
> You get the same error no matter if you connect to internal hostname or through https? E.g.: Internal: http://homeassistant.local:8123 External: https://mypublicdomain.example.com

yes, does not matter if external url or internal ip

**Comment by deluxestyle** [comment] 2024-10-28 14:56
![image](https://github.com/user-attachments/assets/a3fda007-8ce8-4a10-b9b2-6d2fc5c08f60)

not sure if the "source map failed to load" error is related to it

**Comment by BobRobertBob** [comment] 2024-10-28 15:10
Don't have the tech skills you are looking for, but happy to do anything to help that you can walk me through.  In case this helps, I have had this issue on the HA Green, and two installations of HA OS on old Lenovo ThinkPads.  Chrome on Windows 11, Companion App on  iPhone and Wall Panel on Samsung Galaxy Tab S6 Light.  I get the error every time I go to a dashboard with the Sonos Card on it.  Don't have to do anything on the card, just go to a dashboard with it.

**Comment by punxaphil** [comment] 2024-10-28 16:09
Is it just the error in the log, or is something actually not behaving correctly in the card?

**Comment by punxaphil** [comment] 2024-10-28 16:10
@deluxestyle Please try this one: 
https://github.com/punxaphil/custom-sonos-card/releases/tag/v7.21.1

**Comment by deluxestyle** [comment] 2024-10-28 16:12
> @deluxestyle Please try this one: https://github.com/punxaphil/custom-sonos-card/releases/tag/v7.21.1

same error log
the card is working like excpected. only the error is showing up in the log

**Comment by punxaphil** [comment] 2024-10-28 16:14
That's "impossible" 😄 
The new version doesn't log the error about:

_additional error messages
Uncaught (in promise) {code: 'not_found', message: 'Subscription not found.'}_

Are you sure you upgraded and refreshed HA?

**Comment by deluxestyle** [comment] 2024-10-28 16:15
> That's "impossible" 😄 The new version doesn't log the error about:
> 
> _additional error messages Uncaught (in promise) {code: 'not_found', message: 'Subscription not found.'}_
> 
> Are you sure you upgraded and refreshed HA?

ah sorry, did not checked this error. yes, this seems to be away. does not show up

**Comment by BobRobertBob** [comment] 2024-10-28 16:32
I'm still getting error message.  Loaded v7.2.1, restarted HA, reloaded browsers.

**Comment by BobRobertBob** [comment] 2024-10-28 16:33
Make that v7.21.1

**Comment by punxaphil** [comment] 2024-10-28 16:34
Which error?

**Comment by BobRobertBob** [comment] 2024-10-28 16:39
![image](https://github.com/user-attachments/assets/739303d7-e585-4819-a400-86405592999b)

**Comment by punxaphil** [comment] 2024-10-28 16:42
Can you expand that messag?

**Comment by BobRobertBob** [comment] 2024-10-28 17:11
Sorry, cleared that one.  Here is another:

Logger: frontend.js.modern.202410024
Source: components/system_log/__init__.py:331
First occurred: 12:39:26 PM (5 occurrences)
Last logged: 12:44:35 PM

Uncaught error from Chrome 130.0.0.0 on Windows 10 ReferenceError: Cannot access 'e' before initialization Object.callback (/hacsfiles/custom-sonos-card/custom-sonos-card.js:374:977) callback (node_modules/home-assistant-js-websocket/dist/connection.js:23:33) forEach (node_modules/home-assistant-js-websocket/dist/connection.js:15:25)
Uncaught error from Chrome WebView 129.0.6668.102 on Android 14 ReferenceError: Cannot access 'e' before initialization Object.callback (/hacsfiles/custom-sonos-card/custom-sonos-card.js:374:980) callback (node_modules/home-assistant-js-websocket/dist/connection.js:23:33) forEach (node_modules/home-assistant-js-websocket/dist/connection.js:15:25)

**Comment by punxaphil** [comment] 2024-10-28 19:11
That should be fixed now with this:
https://github.com/punxaphil/custom-sonos-card/releases/tag/v7.21.2

**Comment by deluxestyle** [comment] 2024-10-28 19:22
Seems so. Issue is not popping up again

**Comment by punxaphil** [comment] 2024-10-28 20:07
This should fix the sourcemap issue as well.
https://github.com/punxaphil/custom-sonos-card/releases/tag/v7.21.3

Anything else @BobRobertBob @deluxestyle ?
Or are we ready to close this issue.

**Comment by deluxestyle** [comment] 2024-10-28 20:24
Fine from my side to close it
Thank you so much for your work. Much appreciated

**Comment by BobRobertBob** [comment] 2024-10-28 20:25
Tested all devices.  No issues, appears to be fixed.  Thanks so much.  This card is awesome.  Looks so good with all the favorites showing the album art.  I actually installed a HA system for someone who saw mine and wanted it for their Sonos system.  No other Smart Devices, just wanted the dashboard with the Sonos card.

**Comment by BobRobertBob** [comment] 2024-10-28 20:27
Okay to close IMO.

**Comment by punxaphil** [comment] 2024-10-28 20:29
Nice to hear you like it! And that the issues are resolved 😄 
If you have the possibility, please contribute for further development 🙏 


---
PunxaPhil
[![image](https://github.com/user-attachments/assets/cb2e240e-f9ca-4900-a425-b8089216c1ee)](https://patreon.com/PunxaPhil) [![image](https://github.com/johanfrick/custom-sonos-card/assets/26582898/9bebc1f6-6bda-4cbd-b596-50d3d2f712de)](https://www.buymeacoffee.com/punxaphil)

**Closed by punxaphil** 2024-10-28 20:29 UTC
Labels: bug
