### ISSUE TITLE
fallbackArtwork does not remove previous artwork leading to issues with transparency.

### ISSUE THREAD

**Issue by JesperDonnis** [punxaphil/custom-sonos-card#334] opened 2024-03-27 07:17 UTC
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:**

**Last working release (if known):**
Has not worked

**Browser and Operating System:**
Brave is up to date
[Version 1.64.109 Chromium: 123.0.6312.58 (Official Build) (arm64)](https://brave.com/latest/)
MacOS 14.4.1

Issue is the same on other platforms

**Description of problem:**
When adding a new fallback artwork as detailed in the readme.md

fallbackArtwork: https://cdn-icons-png.flaticon.com/512/651/651717.png # Override default fallback artwork image if artwork is missing for the currently selected media.

OR doing the same through the UI settings the default artwork is still rendered leading to issues when the new fallback has transparency.
Please see attached screenshot for details.

**example config showing the issue**
This was made with another icon from the same site as the example in the readme to rule out issues stemming from https issues etc.

type: custom:sonos-card
sections:
  - player
  - volumes
  - groups
  - grouping
  - media browser
topFavorites:
  - DRP4KBH
mediaBrowserShowTitleForThumbnailIcons: true
showVolumeUpAndDownButtons: true
dynamicVolumeSlider: true
entityId: media_player.office
mediaArtworkOverrides:
  - mediaTitleEquals: DR P4 København • P4 er kanalen\
    imageUrl: https://mytuner.global.ssl.fastly.net/media/tvos_radios/WhsVPWQfgR.png
  - ifMissing: true
    imageUrl: https://cdn-icons-png.flaticon.com/128/937/937367.png
widthPercentage: auto
heightPercentage: 100
showAudioInputFormat: true

 
**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

<img width="494" alt="Screenshot 2024-03-27 at 08 17 04" src="https://github.com/punxaphil/custom-sonos-card/assets/51313058/e8263010-9022-4f4e-8262-6fbf16604110">

**Comment by punxaphil** [comment] 2024-03-28 11:09
duplicate of https://github.com/punxaphil/custom-sonos-card/issues/273

**Closed by punxaphil** 2024-03-28 11:09 UTC
Labels: bug
