### ISSUE TITLE
Errors in log

### ISSUE THREAD

**Issue by mfabiani53** [punxaphil/custom-sonos-card#336] opened 2024-04-04 07:38 UTC
**Checklist:**

- [x ] I updated to the latest version available
- [ x] I cleared the cache of my browser

**Release with the issue:**

**Last working release (if known):**

**Browser and Operating System:**
Chrome on Windows 11

**Description of problem:**
Suddenly getting tons of these errors:

2024-04-03 21:30:05.055 ERROR (MainThread) [frontend.js.latest.202403070] Uncaught error from Chrome 123.0.0.0 on Windows 10
ReferenceError: Cannot access 'e' before initialization
Object.callback (/hacsfiles/custom-sonos-card/custom-sonos-card.js:358:980)
callback (node_modules/home-assistant-js-websocket/dist/connection.js:23:33)
forEach (node_modules/home-assistant-js-websocket/dist/connection.js:15:25)
2024-04-03 21:31:20.484 ERROR (MainThread) [frontend.js.latest.202403070] Uncaught error from Chrome 123.0.0.0 on Windows 10
ReferenceError: Cannot access 'e' before initialization
Object.callback (/hacsfiles/custom-sonos-card/custom-sonos-card.js:358:980)
callback (node_modules/home-assistant-js-websocket/dist/connection.js:23:33)
forEach (node_modules/home-assistant-js-websocket/dist/connection.js:15:25)
2024-04-03 21:31:50.604 ERROR (MainThread) [frontend.js.latest.202403070] Uncaught error from Chrome 123.0.0.0 on Windows 10
ReferenceError: Cannot access 'e' before initialization
Object.callback (/hacsfiles/custom-sonos-card/custom-sonos-card.js:358:980)
callback (node_modules/home-assistant-js-websocket/dist/connection.js:23:33)
forEach (node_modules/home-assistant-js-websocket/dist/connection.js:15:25)
2024-04-03 21:35:50.553 ERROR (MainThread) [frontend.js.latest.202403070] Uncaught error from Chrome 123.0.0.0 on Windows 10
ReferenceError: Cannot access 'e' before initialization
Object.callback (/hacsfiles/custom-sonos-card/custom-sonos-card.js:358:980)
callback (node_modules/home-assistant-js-websocket/dist/connection.js:23:33)
forEach (node_modules/home-assistant-js-websocket/dist/connection.js:15:25)
2024-04-03 21:43:11.674 ERROR (MainThread) [frontend.js.latest.202403070] Uncaught error from Chrome 123.0.0.0 on Windows 10
ReferenceError: Cannot access 'e' before initialization
Object.callback (/hacsfiles/custom-sonos-card/custom-sonos-card.js:358:980)
callback (node_modules/home-assistant-js-websocket/dist/connection.js:23:33)
forEach (node_modules/home-assistant-js-websocket/dist/connection.js:15:25)
2024-04-03 21:43:11.723 ERROR (MainThread) [frontend.js.latest.202403070] Uncaught error from Chrome 123.0.0.0 on Windows 10
ReferenceError: Cannot access 'e' before initialization
Object.callback (/hacsfiles/custom-sonos-card/custom-sonos-card.js:358:980)
callback (node_modules/home-assistant-js-websocket/dist/connection.js:23:33)
forEach (node_modules/home-assistant-js-websocket/dist/connection.js:15:25)
2024-04-03 21:49:41.809 ERROR (MainThread) [frontend.js.latest.202403070] Uncaught error from Chrome 123.0.0.0 on Windows 10
ReferenceError: Cannot access 'e' before initialization
Object.callback (/hacsfiles/custom-sonos-card/custom-sonos-card.js:358:980)
callback (node_modules/home-assistant-js-websocket/dist/connection.js:23:33)
forEach (node_modules/home-assistant-js-websocket/dist/connection.js:15:25)
2024-04-03 21:49:41.859 ERROR (MainThread) [frontend.js.latest.202403070] Uncaught error from Chrome 123.0.0.0 on Windows 10
ReferenceError: Cannot access 'e' before initialization
Object.callback (/hacsfiles/custom-sonos-card/custom-sonos-card.js:358:980)
callback (node_modules/home-assistant-js-websocket/dist/connection.js:23:33)
forEach (node_modules/home-assistant-js-websocket/dist/connection.js:15:25)

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by punxaphil** [comment] 2024-04-04 09:45
Do you notice any problems in the card?

**Comment by mfabiani53** [comment] 2024-04-04 10:31
No, nothing strange

**Comment by punxaphil** [comment] 2024-04-05 17:53
You think any changes are needed in the Sonos card?

**Comment by thlucas1** [comment] 2024-04-05 18:03
@punxaphil 
I put defensive code in my media player integrations to handle it, but it might still cause issues with other media players that don't expect it.  

Would it be possible to bypass the `async_browse_media` request (with `media_content_type = favorites`) when a non-Sonos media player is selected in the Sonos Card UI?   If I am thinking correctly, this is being done by the Sonos Card and not the media browser component?  Not sure.

**Comment by mfabiani53** [comment] 2024-04-06 12:10
Still getting same erros also after uninstalling spotifyplus integration..
2024-04-06 13:12:23.771 ERROR (MainThread) [frontend.js.latest.202403070] Uncaught error from Chrome 123.0.0.0 on Windows 10
ReferenceError: Cannot access 'e' before initialization
Object.callback (/hacsfiles/custom-sonos-card/custom-sonos-card.js:358:980)
callback (node_modules/home-assistant-js-websocket/dist/connection.js:23:33)
forEach (node_modules/home-assistant-js-websocket/dist/connection.js:15:25)
2024-04-06 13:25:53.834 ERROR (MainThread) [frontend.js.latest.202403070] Uncaught error from Chrome 123.0.0.0 on Windows 10
ReferenceError: Cannot access 'e' before initialization
Object.callback (/hacsfiles/custom-sonos-card/custom-sonos-card.js:358:980)
callback (node_modules/home-assistant-js-websocket/dist/connection.js:23:33)
forEach (node_modules/home-assistant-js-websocket/dist/connection.js:15:25)
2024-04-06 13:26:53.811 ERROR (MainThread) [frontend.js.latest.202403070] Uncaught error from Chrome 123.0.0.0 on Windows 10
ReferenceError: Cannot access 'e' before initialization
Object.callback (/hacsfiles/custom-sonos-card/custom-sonos-card.js:358:980)
callback (node_modules/home-assistant-js-websocket/dist/connection.js:23:33)
forEach (node_modules/home-assistant-js-websocket/dist/connection.js:15:25)
2024-04-06 13:29:44.563 ERROR (MainThread) [frontend.js.latest.202403070] Uncaught error from Chrome 123.0.0.0 on Windows 10
ReferenceError: Cannot access 'e' before initialization
Object.callback (/hacsfiles/custom-sonos-card/custom-sonos-card.js:358:980)
callback (node_modules/home-assistant-js-websocket/dist/connection.js:23:33)
forEach (node_modules/home-assistant-js-websocket/dist/connection.js:15:25)
2024-04-06 13:29:53.963 ERROR (MainThread) [frontend.js.latest.202403070] Uncaught error from Chrome 123.0.0.0 on Windows 10
ReferenceError: Cannot access 'e' before initialization
Object.callback (/hacsfiles/custom-sonos-card/custom-sonos-card.js:358:980)
callback (node_modules/home-assistant-js-websocket/dist/connection.js:23:33)
forEach (node_modules/home-assistant-js-websocket/dist/connection.js:15:25)
2024-04-06 13:35:09.678 ERROR (MainThread) [frontend.js.latest.202403070] Uncaught error from Chrome 123.0.0.0 on Windows 10
ReferenceError: Cannot access 'e' before initialization
Object.callback (/hacsfiles/custom-sonos-card/custom-sonos-card.js:358:980)
callback (node_modules/home-assistant-js-websocket/dist/connection.js:23:33)
forEach (node_modules/home-assistant-js-websocket/dist/connection.js:15:25)
2024-04-06 13:38:24.663 ERROR (MainThread) [frontend.js.latest.202403070] Uncaught error from Chrome 123.0.0.0 on Windows 10
ReferenceError: Cannot access 'e' before initialization
Object.callback (/hacsfiles/custom-sonos-card/custom-sonos-card.js:358:980)
callback (node_modules/home-assistant-js-websocket/dist/connection.js:23:33)
forEach (node_modules/home-assistant-js-websocket/dist/connection.js:15:25)
2024-04-06 13:39:07.552 ERROR (MainThread) [frontend.js.latest.202403070] Uncaught error from Chrome 123.0.0.0 on Windows 10
ReferenceError: Cannot access 'e' before initialization
Object.callback (/hacsfiles/custom-sonos-card/custom-sonos-card.js:358:980)
callback (node_modules/home-assistant-js-websocket/dist/connection.js:23:33)
forEach (node_modules/home-assistant-js-websocket/dist/connection.js:15:25)
2024-04-06 13:40:23.774 ERROR (MainThread) [frontend.js.latest.202403070] Uncaught error from Chrome 123.0.0.0 on Windows 10
ReferenceError: Cannot access 'e' before initialization
Object.callback (/hacsfiles/custom-sonos-card/custom-sonos-card.js:358:980)
callback (node_modules/home-assistant-js-websocket/dist/connection.js:23:33)
forEach (node_modules/home-assistant-js-websocket/dist/connection.js:15:25)
2024-04-06 13:43:23.714 ERROR (MainThread) [frontend.js.latest.202403070] Uncaught error from Chrome 123.0.0.0 on Windows 10
ReferenceError: Cannot access 'e' before initialization
Object.callback (/hacsfiles/custom-sonos-card/custom-sonos-card.js:358:980)
callback (node_modules/home-assistant-js-websocket/dist/connection.js:23:33)
forEach (node_modules/home-assistant-js-websocket/dist/connection.js:15:25)
2024-04-06 13:45:31.360 ERROR (MainThread) [frontend.js.latest.202403070] Uncaught error from Chrome 123.0.0.0 on Windows 10
ReferenceError: Cannot access 'e' before initialization
Object.callback (/hacsfiles/custom-sonos-card/custom-sonos-card.js:358:980)
callback (node_modules/home-assistant-js-websocket/dist/connection.js:23:33)
forEach (node_modules/home-assistant-js-websocket/dist/connection.js:15:25)
2024-04-06 13:45:31.724 ERROR (MainThread) [frontend.js.latest.202403070] Uncaught error from Chrome 123.0.0.0 on Windows 10
ReferenceError: Cannot access 'e' before initialization
Object.callback (/hacsfiles/custom-sonos-card/custom-sonos-card.js:358:980)
callback (node_modules/home-assistant-js-websocket/dist/connection.js:23:33)
forEach (node_modules/home-assistant-js-websocket/dist/connection.js:15:25)
2024-04-06 13:47:31.587 ERROR (MainThread) [frontend.js.latest.202403070] Uncaught error from Chrome 123.0.0.0 on Windows 10
ReferenceError: Cannot access 'e' before initialization
Object.callback (/hacsfiles/custom-sonos-card/custom-sonos-card.js:358:980)
callback (node_modules/home-assistant-js-websocket/dist/connection.js:23:33)
forEach (node_modules/home-assistant-js-websocket/dist/connection.js:15:25)

**Comment by thlucas1** [comment] 2024-04-07 14:26
@mfabiani53 I will let @punxaphil address the `ReferenceError` issues you are having, as it appears it's coming from the `custom-sonos-card.js` module.

**Comment by punxaphil** [comment] 2024-04-08 05:58
I can't reproduce this. What do you see if you click on this line?
`/hacsfiles/custom-sonos-card/custom-sonos-card.js:358:980`

**Comment by mfabiani53** [comment] 2024-04-08 12:06
I also noticed the error happens only when i try to edit the card via GUI.

**Comment by mfabiani53** [comment] 2024-04-08 12:35
> I can't reproduce this. What do you see if you click on this line? `/hacsfiles/custom-sonos-card/custom-sonos-card.js:358:980`

I get this:

![image](https://github.com/punxaphil/custom-sonos-card/assets/37701688/4b949289-e8e2-4c6d-b9cc-6ddb8e893ad1)

**Comment by mfabiani53** [comment] 2024-04-08 12:41
I tried again after clearing cache on both andorid device and Chrome on windows 11
This is the result:

2024-04-08 14:38:07.736 ERROR (MainThread) [frontend.js.latest.202404041] Uncaught error from Chrome WebView 124.0.6367.28 on Android 14
Script error.
null
@:0:0
2024-04-08 14:39:31.644 ERROR (MainThread) [frontend.js.latest.202404041] Uncaught error from Chrome 123.0.0.0 on Windows 10
ReferenceError: Cannot access 'e' before initialization
Object.callback (/hacsfiles/custom-sonos-card/custom-sonos-card.js:358:980)
callback (node_modules/home-assistant-js-websocket/dist/connection.js:23:33)
forEach (node_modules/home-assistant-js-websocket/dist/connection.js:15:25)

**Comment by punxaphil** [comment] 2024-04-08 19:55
> I also noticed the error happens only when i try to edit the card via GUI.

Can you share a video of this?

**Comment by mfabiani53** [comment] 2024-04-09 07:33
Sorry, i can't, but the steps are very simple. I go to the dashboard, click edit and do some changes in the code... in that moment the log gets populated of those errors.... sometimes i don't do any change in the code, but the errors come the same way....
Hope this helps...

**Comment by punxaphil** [comment] 2024-04-09 07:55
Not really. I've tried that. No errors for me

**Comment by mfabiani53** [comment] 2024-04-09 07:57
So, what you advice for me?

**Comment by mfabiani53** [comment] 2024-04-09 08:03
Strange is that i begin to see those errors only after i switched from yaml to storage mode in editing the dashboard.
Did you tried to use storage mode and then edit the dashboard?

**Comment by mfabiani53** [comment] 2024-04-09 08:05
In case, this is my lovelace dashboard about sonos:

``
{
  "version": 1,
  "minor_version": 1,
  "key": "lovelace.sonos_2",
  "data": {
    "config": {
      "views": [
        {
          "title": "Sonos",
          "path": "sonos",
          "icon": "phu:sonos-one",
          "theme": "rounded",
          "cards": [
            {
              "type": "grid",
              "square": false,
              "columns": 1,
              "cards": [
                {
                  "type": "custom:button-card",
                  "name": "Musica su Sonos",
                  "styles": {
                    "card": [
                      {
                        "--mdc-ripple-color": "blue"
                      },
                      {
                        "--mdc-ripple-press-opacity": 0.5
                      },
                      {
                        "font-size": "14px"
                      },
                      {
                        "font-weight": "bold"
                      }
                    ]
                  },
                  "tap_action": {
                    "action": "fire-dom-event",
                    "browser_mod": {
                      "command": "call-service",
                      "service": "script.scelta_musica_sonos"
                    }
                  }
                }
              ]
            },
            {
              "type": "custom:sonos-card",
              "sections": [
                "player",
                "volumes",
                "groups"
              ],
              "entityId": "media_player.studio",
              "showVolumeUpAndDownButtons": false,
              "topFavorites": [
                ""
              ],
              "dynamicVolumeSlider": true,
              "numberOfFavoritesToShow": 50,
              "showAudioInputFormat": true,
              "adjustVolumeRelativeToMainPlayer": true,
              "hideBrowseMediaButton": false,
              "heightPercentage": 100,
              "artworkAsBackground": true,
              "artworkMinHeight": 10,
              "widthPercentage": 100,
              "mediaBrowserItemsPerRow": 4,
              "dynamicVolumeSliderMax": 30,
              "showNonSonosPlayers": false,
              "mediaArtworkOverrides": [
                {
                  "ifMissing": false,
                  "sizePercentage": 100
                }
              ],
              "dynamicVolumeSliderThreshold": 20,
              "hideGroupCurrentTrack": false,
              "view_layout": {
                "position": "main"
              },
              "card_mod": {
                "style": {
                  ".": "",
                  "sonos-player$": ".controls {\n  background-color: rgba(var(--rgb-card-background-color), 0.4) !important;\n}\nsonos-player-header {\n  background-color: rgba(var(--rgb-card-background-color), 0.4) !important;\n}      \n",
                  "sonos-player$ sonos-player-controls$": ".icons * {    \n  --mdc-icon-button-size: 3rem !important;\n  --mdc-icon-size: 2rem !important;\n} \nha-icon-button {\n  display: none !important;\n}\n",
                  "sonos-player$ sonos-player-controls$ sonos-volume$": "ha-control-slider {\n  height: 14px !important;\n} \n"
                }
              }
            },
            {
              "type": "custom:sonos-card",
              "theme": "rounded",
              "sections": [
                "media browser"
              ],
              "mediaBrowserItemsPerRow": 3,
              "card_mod": {
                "style": {
                  "sonos-media-browser$ sonos-media-browser-icons$": "div {            \n  border: 1px solid blue;\n  color: red !important;\n}\n"
                }
              }
            }
          ],
          "type": "custom:masonry-layout"
        }
      ],
      "title": ""
    }
  }
}
``

**Comment by mfabiani53** [comment] 2024-04-09 08:07
or better:

{
  "version": 1,
  "minor_version": 1,
  "key": "lovelace.sonos_2",
  "data": {
    "config": {
      "views": [
        {
          "title": "Sonos",
          "path": "sonos",
          "icon": "phu:sonos-one",
          "theme": "rounded",
          "cards": [
            {
              "type": "grid",
              "square": false,
              "columns": 1,
              "cards": [
                {
                  "type": "custom:button-card",
                  "name": "Musica su Sonos",
                  "styles": {
                    "card": [
                      {
                        "--mdc-ripple-color": "blue"
                      },
                      {
                        "--mdc-ripple-press-opacity": 0.5
                      },
                      {
                        "font-size": "14px"
                      },
                      {
                        "font-weight": "bold"
                      }
                    ]
                  },
                  "tap_action": {
                    "action": "fire-dom-event",
                    "browser_mod": {
                      "command": "call-service",
                      "service": "script.scelta_musica_sonos"
                    }
                  }
                }
              ]
            },
            {
              "type": "custom:sonos-card",
              "sections": [
                "player",
                "volumes",
                "groups"
              ],
              "entityId": "media_player.studio",
              "showVolumeUpAndDownButtons": false,
              "topFavorites": [
                ""
              ],
              "dynamicVolumeSlider": true,
              "numberOfFavoritesToShow": 50,
              "showAudioInputFormat": true,
              "adjustVolumeRelativeToMainPlayer": true,
              "hideBrowseMediaButton": false,
              "heightPercentage": 100,
              "artworkAsBackground": true,
              "artworkMinHeight": 10,
              "widthPercentage": 100,
              "mediaBrowserItemsPerRow": 4,
              "dynamicVolumeSliderMax": 30,
              "showNonSonosPlayers": false,
              "mediaArtworkOverrides": [
                {
                  "ifMissing": false,
                  "sizePercentage": 100
                }
              ],
              "dynamicVolumeSliderThreshold": 20,
              "hideGroupCurrentTrack": false,
              "view_layout": {
                "position": "main"
              },
              "card_mod": {
                "style": {
                  ".": "",
                  "sonos-player$": ".controls {\n  background-color: rgba(var(--rgb-card-background-color), 0.4) !important;\n}\nsonos-player-header {\n  background-color: rgba(var(--rgb-card-background-color), 0.4) !important;\n}      \n",
                  "sonos-player$ sonos-player-controls$": ".icons * {    \n  --mdc-icon-button-size: 3rem !important;\n  --mdc-icon-size: 2rem !important;\n} \nha-icon-button {\n  display: none !important;\n}\n",
                  "sonos-player$ sonos-player-controls$ sonos-volume$": "ha-control-slider {\n  height: 14px !important;\n} \n"
                }
              }
            },
            {
              "type": "custom:sonos-card",
              "theme": "rounded",
              "sections": [
                "media browser"
              ],
              "mediaBrowserItemsPerRow": 3,
              "card_mod": {
                "style": {
                  "sonos-media-browser$ sonos-media-browser-icons$": "div {            \n  border: 1px solid blue;\n  color: red !important;\n}\n"
                }
              }
            }
          ],
          "type": "custom:masonry-layout"
        }
      ],
      "title": ""
    }
  }
}

**Comment by punxaphil** [comment] 2024-04-09 09:39
please wrap the code in three backticks prior, and three backticks in the end
![image](https://github.com/punxaphil/custom-sonos-card/assets/26582898/2b16cec8-1dea-420b-a376-f30a7e90d58d)

**Comment by mfabiani53** [comment] 2024-04-09 10:30
```
{
  "version": 1,
  "minor_version": 1,
  "key": "lovelace.sonos_2",
  "data": {
    "config": {
      "views": [
        {
          "title": "Sonos",
          "path": "sonos",
          "icon": "phu:sonos-one",
          "theme": "rounded",
          "cards": [
            {
              "type": "grid",
              "square": false,
              "columns": 1,
              "cards": [
                {
                  "type": "custom:button-card",
                  "name": "Musica su Sonos",
                  "styles": {
                    "card": [
                      {
                        "--mdc-ripple-color": "blue"
                      },
                      {
                        "--mdc-ripple-press-opacity": 0.5
                      },
                      {
                        "font-size": "14px"
                      },
                      {
                        "font-weight": "bold"
                      }
                    ]
                  },
                  "tap_action": {
                    "action": "fire-dom-event",
                    "browser_mod": {
                      "command": "call-service",
                      "service": "script.scelta_musica_sonos"
                    }
                  }
                }
              ]
            },
            {
              "type": "custom:sonos-card",
              "sections": [
                "player",
                "volumes",
                "groups"
              ],
              "entityId": "media_player.studio",
              "showVolumeUpAndDownButtons": false,
              "topFavorites": [
                ""
              ],
              "dynamicVolumeSlider": true,
              "numberOfFavoritesToShow": 50,
              "showAudioInputFormat": true,
              "adjustVolumeRelativeToMainPlayer": true,
              "hideBrowseMediaButton": false,
              "heightPercentage": 100,
              "artworkAsBackground": true,
              "artworkMinHeight": 10,
              "widthPercentage": 100,
              "mediaBrowserItemsPerRow": 4,
              "dynamicVolumeSliderMax": 30,
              "showNonSonosPlayers": false,
              "mediaArtworkOverrides": [
                {
                  "ifMissing": false,
                  "sizePercentage": 100
                }
              ],
              "dynamicVolumeSliderThreshold": 20,
              "hideGroupCurrentTrack": false,
              "view_layout": {
                "position": "main"
              },
              "card_mod": {
                "style": {
                  ".": "",
                  "sonos-player$": ".controls {\n  background-color: rgba(var(--rgb-card-background-color), 0.4) !important;\n}\nsonos-player-header {\n  background-color: rgba(var(--rgb-card-background-color), 0.4) !important;\n}      \n",
                  "sonos-player$ sonos-player-controls$": ".icons * {    \n  --mdc-icon-button-size: 3rem !important;\n  --mdc-icon-size: 2rem !important;\n} \nha-icon-button {\n  display: none !important;\n}\n",
                  "sonos-player$ sonos-player-controls$ sonos-volume$": "ha-control-slider {\n  height: 14px !important;\n} \n"
                }
              }
            },
            {
              "type": "custom:sonos-card",
              "theme": "rounded",
              "sections": [
                "media browser"
              ],
              "mediaBrowserItemsPerRow": 3,
              "card_mod": {
                "style": {
                  "sonos-media-browser$ sonos-media-browser-icons$": "div {            \n  border: 1px solid blue;\n  color: red !important;\n}\n"
                }
              }
            }
          ],
          "type": "custom:masonry-layout"
        }
      ],
      "title": ""
    }
  }
}
```

**Comment by mfabiani53** [comment] 2024-04-11 18:19
Still getting always the same errors.......

**Comment by mfabiani53** [comment] 2024-04-11 18:45
This from home assistent:

Registratore: frontend.js.latest.202404041
Fonte: components/system_log/__init__.py:320
Prima occorrenza: 15:17:50 (14 occorrenze)
Ultima registrazione: 20:40:45

Uncaught error from Chrome WebView 124.0.6367.28 on Android 14 Script error. null @:0:0
Uncaught error from Chrome 123.0.0.0 on Windows 10 ReferenceError: Cannot access 'e' before initialization Object.callback (/hacsfiles/custom-sonos-card/custom-sonos-card.js:366:980) callback (node_modules/home-assistant-js-websocket/dist/connection.js:23:33) forEach (node_modules/home-assistant-js-websocket/dist/connection.js:15:25)

**Comment by mfabiani53** [comment] 2024-04-11 18:46
> Yeah, I recommend you going back to yaml mode

Ok, i'll try...

**Comment by mfabiani53** [comment] 2024-04-12 07:02
> Yeah, I recommend you going back to yaml mode

Sorry, but switching to yaml mode doesn't change.
Errors are still there.. always referring to webview I. Chrome desktop or in Android app.

**Comment by mfabiani53** [comment] 2024-04-12 10:21
Also on Chrome running on my IMac....

2024-04-12 12:17:52.169 ERROR (MainThread) [frontend.js.latest.202404041] Uncaught error from Chrome 116.0.0.0 on Mac OS 10.15.7
ReferenceError: Cannot access 'e' before initialization
Object.callback (/hacsfiles/custom-sonos-card/custom-sonos-card.js:366:980)
callback (node_modules/home-assistant-js-websocket/dist/connection.js:23:33)
forEach (node_modules/home-assistant-js-websocket/dist/connection.js:15:25)

**Comment by punxaphil** [comment] 2024-04-12 10:28
Any ad blockers?

**Comment by mfabiani53** [comment] 2024-04-12 10:30
no, nothing...

**Comment by mfabiani53** [comment] 2024-04-12 10:54
If using Edge on my windows 11 desktop i don't get those errors...
Hope all this will help you....

**Comment by punxaphil** [comment] 2024-04-12 12:46
Try both local and external URL to home assistant

**Comment by mfabiani53** [comment] 2024-04-12 14:29
I think i have solved the issue...
I did a '**ha core rebuild**', restarted completely the raspberry and Home Assistant and now **it seems** i have no more errors...
Finger crossing...

**Comment by punxaphil** [comment] 2024-04-12 14:30
what kind of ha setup is that?? I have never run such a command

**Comment by mfabiani53** [comment] 2024-04-12 14:32
I have HAOS running on a Raspberry Pi4

**Comment by punxaphil** [comment] 2024-04-12 14:34
custom build or something? I just do updates in the settings section in the UI. 
**rebuild** sounds like something else than the standard installation

**Comment by mfabiani53** [comment] 2024-04-12 14:36
It's a terminal command i run from the ssh terminal.
No custom build.. i read this in the community forum about a bug in the previous supervisor.

**Comment by punxaphil** [comment] 2024-04-12 14:37
Alright. News to me. 
Closing the issue then.

**Comment by mfabiani53** [comment] 2024-04-12 14:38
I hope all is fixed... in case i'll let you know.

**Closed by punxaphil** 2024-04-12 14:37 UTC
Labels: bug

**Comment by BobRobertBob** [comment] 2024-10-02 14:33
I am having the same issue:

Logger: frontend.js.modern.202409091
Source: components/system_log/__init__.py:333
First occurred: 10:13:36 AM (9 occurrences)
Last logged: 10:19:34 AM

Uncaught error from Chrome WebView 128.0.6613.146 on Android 14 ReferenceError: Cannot access 'e' before initialization Object.callback (/hacsfiles/custom-sonos-card/custom-sonos-card.js:381:980) callback (node_modules/home-assistant-js-websocket/dist/connection.js:23:33) forEach (node_modules/home-assistant-js-websocket/dist/connection.js:15:25)

Uncaught error from Chrome 129.0.0.0 on Windows 10 ReferenceError: Cannot access 'e' before initialization Object.callback (/hacsfiles/custom-sonos-card/custom-sonos-card.js:381:980) callback (node_modules/home-assistant-js-websocket/dist/connection.js:23:33) forEach (node_modules/home-assistant-js-websocket/dist/connection.js:15:25)

Uncaught error from Chrome WebView 120.0.6099.266 on Android 11 ReferenceError: Cannot access 'e' before initialization Object.callback (/hacsfiles/custom-sonos-card/custom-sonos-card.js:381:980) callback (node_modules/home-assistant-js-websocket/dist/connection.js:23:33) forEach (node_modules/home-assistant-js-websocket/dist/connection.js:15:25)

Errors are generated anytime I access a Dashboard with the Sonos Card, I don't have to click on the card.  I tried "ha core rebuild" mentioned above, no change.  Not running Spotify.  No issue with the functionality of the card itself.  As you can see from the logs, this happens on Windows (Chrome) as well as on two different Androids.

**Comment by punxaphil** [comment] 2024-10-28 20:20
If anyone still saw these errors, I hope they are fixed now with this:

https://github.com/punxaphil/custom-sonos-card/releases/tag/v7.21.3
